name: ✨ 機能要求 / Feature Request
description: 新しい機能や改善の提案はこちら
title: "[✨Feature] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        **新機能の提案ありがとうございます！以下の内容をできるだけ詳しく記入してください。**

  - type: textarea
    id: feature-description
    attributes:
      label: 機能の概要
      description: どのような機能を追加したいか、何ができるようになるかを詳しく書いてください。
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 動機・背景
      description: なぜこの機能が必要なのか、どのような場面で使うのかを説明してください。
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: どのようにこの機能を実装するか、APIの設計案があれば記載してください。
      placeholder: |
        例：
        ```csharp
        await ttsClient.NewFeatureAsync(parameters);
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる実装方法や回避策があれば記載してください。
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: 参考資料、関連するissue、スクリーンショットなどがあれば記載してください。
    validations:
      required: false