name: publish nuget
on:
  release:
    types: [published]

env:
  PROJECT_PATH: 'src/Aivis.Net.csproj'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME="${GITHUB_REF##*/}"             # e.g. v1.2.3
          VERSION="${TAG_NAME#v}"                  # remove leading 'v'
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # リリースノートはGitHubのリリースから取得
      - name: Get release notes
        id: notes
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          gh release view ${{ github.ref_name }} --json body -q '.body' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      # Pack: PowerShell で安全に多行文字列を渡す
      - name: Pack the NuGet package (safe)
        shell: pwsh
        run: |
          $notes = @'
      ${{ steps.notes.outputs.notes }}
      '@
          dotnet pack $env:PROJECT_PATH `
            --configuration Release `
            --no-build `
            --output ./nupkg `
            -p:Version='${{ steps.version.outputs.version }}' `
            -p:PackageReleaseNotes="$notes"

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

